[build-system]
requires = ["setuptools", "setuptools-scm[toml]", "wheel", "twine"]

[tool.black]
line-length = 99
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | build
    | dist
  )/
  | _version\.py
)
'''
